### ISSUE TITLE
clientside leaves bug

### ISSUE THREAD

**Issue by bkgktp** [HibiscusMC/HMCLeaves#14]
Server Version: purpurmc-1.20.1-2017-build

HMCLeaves Version:1.3.0

This is a rare issue when I turn the server on or off or sometimes. The block is sent only from the client side and disappears once you click on it. this happens not just for the leaves but sometimes for the seedlings.

https://streamable.com/wsresu

here is a video that my players sent me.

**Comment by Fisher2911** [comment]
I'll need some more information:

- Server software and version
- Debug tool output
- Plugin version

**Comment by bkgktp** [comment]
same error works for both lobby and skyblock server. i will give information of my lobby server.

<img width="442" alt="image" src="https://github.com/HibiscusMC/HMCLeaves/assets/101702786/9deec247-702f-475a-a448-6a87ebfca50f">

<img width="747" alt="image" src="https://github.com/HibiscusMC/HMCLeaves/assets/101702786/2ca7e368-8df0-4673-952f-2bdc3022f717">

<img width="299" alt="image" src="https://github.com/HibiscusMC/HMCLeaves/assets/101702786/8c645fb2-9330-43e9-ab32-030d839516d6">

**Comment by Fisher2911** [comment]
Can you send it in a video? I cannot tell what is going on from that image

**Comment by bkgktp** [comment]
https://streamable.com/wsresu

I can't get an updated video recording right now but you can watch it.

**Comment by bkgktp** [comment]
https://streamable.com/1v25bn

ok, i made a video for you again, that's exactly how it happens.

**Comment by Fisher2911** [comment]
Did you reset your database when you updated to the released version?

**Comment by bkgktp** [comment]
yes i reset the database.

**Comment by Fisher2911** [comment]
Can you send the database so I can take a look?

**Comment by Fisher2911** [comment]
This should be fixed with the latest update.
