### ISSUE TITLE
[SUGGESTION] Make us able to place vines in the ceiling/floor with different IDs

### ISSUE THREAD

**Issue by MarkinhosMLP** [HibiscusMC/HMCLeaves#17]
![image](https://github.com/HibiscusMC/HMCLeaves/assets/47507632/9f6a258b-bfa9-4fc8-a268-b3acdd94e07e)

so we can use one item only to place it up and down

**Comment by Fisher2911** [comment]
I’ll add some API events so this feature can be made using the API, but I don’t plan on adding this feature myself at the moment, I may at a later date
