### ISSUE TITLE
Creative bug (maybe future)

### ISSUE THREAD

**Issue by matyasvane** [HibiscusMC/HMCLeaves#2]
Hey again, 

https://user-images.githubusercontent.com/75536352/202969291-729cd847-73d0-4511-83d7-f213664febcf.mp4

When I'm in creative mode and looking at the custom list, it happens that when I try to pull an item from the inventory it starts to replace it.

+ Is there a way to make it not decay in creative mode + or work using set data from plugins? Some plugins have the ability to block the disintegration of leaves (for example, WorldGuard).

**Comment by Fisher2911** [comment]
Hey, unfortunately this is a bug with creative mode middle click that may not be able to be fixed, but I can add a toggle option in the config.
WorldEdit + WorldGuard support are in the works too.

You said
"Is there a way to make it not crash in creative mode"
Is it crashing when you are in creative, or was that just a typo?

**Comment by matyasvane** [comment]
That's another matter, watch:

https://vimeo.com/773191811

**Comment by Fisher2911** [comment]
The reason this happens is because as far as I have seen, it is not possible to distinguish between a creative click on a block, and a creative click in the inventory. For now, just try not to look at leaves when in the creative inventory.

Just to clarify though, it doesn't crash right?

**Comment by matyasvane** [comment]
No, the server is running fine. By the way, I noticed that the lay down animation is not done. Is this due to the fact that it is a PAPER item?

**Comment by Fisher2911** [comment]
Oh shoot, that was added before but I completely redid how the plugin worked and forgot to add it back.
I'll add that back in the next update, sorry about that!

**Comment by Fisher2911** [comment]
Oh I also just noticed you wanted a way to make them not decay in creative, what you can do is set actually-persistent: true
in the config for the leaf item you want to stay persistent when placed.
