### ISSUE TITLE
[BUG] berries in "cave_vines_plant" transform it into "cave_vines"

### ISSUE THREAD

**Issue by MarkinhosMLP** [HibiscusMC/HMCLeaves#21]
well, tbh i dont understand since the plugin does not mess with the "cave_vines_plant" block but only the "cave_vines" one
as you can see in the video, the block id changes

https://github.com/HibiscusMC/HMCLeaves/assets/47507632/fc28d0cb-bf20-4f10-94a9-320297b55ad9

it makes the vanilla models look bad

No Berries
![image](https://github.com/HibiscusMC/HMCLeaves/assets/47507632/ee7993e3-9fec-40a4-8bda-21fa3153f54f)
With Berries (Vanilla)
![image](https://github.com/HibiscusMC/HMCLeaves/assets/47507632/ab5b1777-71ad-482f-b920-c49484a9ff48)
With Berries (HMC Leaves)
![image](https://github.com/HibiscusMC/HMCLeaves/assets/47507632/1b93f5d0-8696-422b-b8d5-7f2ba1763b4c)

**Comment by Fisher2911** [comment]
This was fixed
