### ISSUE TITLE
[Bug] Custom leaves only drop vanilla items

### ISSUE THREAD

**Issue by AllayBreeze** [HibiscusMC/HMCLeaves#24]
When breaking the custom leaves it always drop vanilla items. (e.c. the test leaves drop oak leaves or oak saplings).
Considering the issue in #23, It'll also be good if there can be configuration that define the drop rate of custom saplings.

Server: git-Purpur-2011 (MC: 1.20.1)
HMCLeaves version 1.0.5

**Comment by Fisher2911** [comment]
Can you send your config and a video of the issue?

**Comment by AllayBreeze** [comment]
I think I have found the reason. It seems to be an incompatibility with another plugin (called Nova), and independently using HMCLeaves won't cause this issue. 
I'm gonna close it. Sorry for the inconvenience
