### ISSUE TITLE
[Bug] Stripping not working correctly if by right clicking the log through incomplete blocks

### ISSUE THREAD

**Issue by AllayBreeze** [HibiscusMC/HMCLeaves#26]
https://github.com/HibiscusMC/HMCLeaves/assets/108282297/c8faf2aa-4352-43d4-81f6-7ed15bded8f1

If player strip the log from a direction that contains an incomplete block (such as snow layer/pointed dripstone in the video), the log will turn back to vanilla log.

Server version git-Purpur-2005 (MC: 1.20.1)
HMCLeaves version 1.0.5
Bukkit Plugins: (3): HMCLeaves, ProtocolLib, spark
Log config:
`  baobab_log:`
`    log-material: OAK_LOG`
`    stripped-log-material: STRIPPED_OAK_LOG`
`    stripped-log-id: stripped_baobab_log`
`    stripped-log:`
`      inventory-item:`
`        material: PAPER`
`        model-data: 1`
`        name: "stripped_baobab_log"`
`        lore: []`
`    material: PAPER`
`    model-data: 1`
`    name: "baobab_log"`
`    lore: []`
`    instrument: BASEDRUM`
`    note: 1`
`    stripped-instrument: BASEDRUM`
`    stripped-note: 4`
`    generate-axes: true`
`    model-path: "example:block/baobab_log"`

**Comment by Fisher2911** [comment]
This was fixed
