### ISSUE TITLE
[SUGGESTION] set leaves distance to fall

### ISSUE THREAD

**Issue by MarkinhosMLP** [HibiscusMC/HMCLeaves#29]
Here is my idea: i want to make some leaves really large in the trees **that will be grown naturally/with saplings** so im making the schematics here, but sometimes it is in the distance 7. Leaves breaks and fall down when it has the distance 7, except of course, if it is persistent

https://youtu.be/6PsqnTy0buI

my idea is that you can create an item which places the leaves with an specific distance, like 6 for example, so it wont fall, except if you cut the whole tree, so i can create the tree with the leaves where i want and it wont fall till someone breaks the tree
or even an option to decide like "Leaves will fall only when 9 blocks away from the log" but since we dont have the blockstate for distance 9, if you place a block and its 7 or 8 blocks away from a log, instead of placing it with the server distance=7, it would be placed with server distance=6

**Comment by Fisher2911** [comment]
This isn't planned as I would have to rewrite the whole leaf system
