### ISSUE TITLE
Oraxen blocks cannot be placed and will not put the correct block variation when placed.

### ISSUE THREAD

**Issue by bkgktp** [HibiscusMC/HMCLeaves#30]
After updating the plugin I realized that it is incompatible with Oraxen. the plugin is not configurable at all and the blocks do not work as intended.

You can find the detailed video of the error at this link.
https://streamable.com/8zn6l7

myserver full logs:
https://mclo.gs/agvQPf8

HMCLeaves/logs.yml
https://mclo.gs/fO91W9R

Oraxen/item.yml
https://mclo.gs/7Fs0Bsp

<img width="669" alt="resim" src="https://github.com/HibiscusMC/HMCLeaves/assets/101702786/1440ba9a-9fbc-415d-a40d-b762e8a03eaa">

<img width="375" alt="resim" src="https://github.com/HibiscusMC/HMCLeaves/assets/101702786/4a94a3e2-350c-411c-a39f-8d3602b71e0e">

the error works quite messy logs blocks are not working as expected and sync with oraxen is not working. When we place the blocks, he places two each.

A setting that adds the directions of the directional blocks one by one into the configuration would be nice.

I don't think it's a configuration error. When the "generate-axes" setting is on, textures/note_block.json doesn't merge with oraxen, so this setting doesn't work properly with oraxen. A setting where we can specify the data of the direction blocks one by one would be really nice, or it could be corrected in an existing way.

Coming to the preamble of the error, I updated Oraxen and HMCLeaves and after updating I encountered such an event. this is weird

**Comment by Fisher2911** [comment]
You should not have generate-axes enabled when you use Oraxen

**Comment by bkgktp** [comment]
yes I disabled it but it still doesn't work

**Comment by bkgktp** [comment]
<img width="726" alt="resim" src="https://github.com/HibiscusMC/HMCLeaves/assets/101702786/b0d23b18-d5fc-433c-beb6-c3b30a195e58">

**Comment by Fisher2911** [comment]
It appears to be an issue with your configuration, please use the discord to get support

**Comment by bkgktp** [comment]
This is a Bug request, not a support request. I've been using the plugin since the first day you coded it. There is such a problem. This error should be resolved.

**Comment by Fisher2911** [comment]
It’s an issue with the way you set up the plugin, not a bug on my end

**Comment by bkgktp** [comment]
yes I think I have solved it but the plugin has some minor issues, I have reported them and notified you via discord, thanks for your feedback.
