### ISSUE TITLE
[FEATURE REQUEST] World edit Schematics Compatibility

### ISSUE THREAD

**Issue by SebyRo23** [HibiscusMC/HMCLeaves#4]
Since both IA and Oraxen has added world edit compatibility, I think it would make sense to add Compatibility with World Edit Schematics.

**Comment by Phoenix-99** [comment]
Yeah, i think the same! It will really nice have custom shapes for our trees when they grow up!! I hope it arrive soon!

**Comment by Fisher2911** [comment]
WorldEdit schematics are now supported as of version 1.3.0-beta.
