### ISSUE TITLE
Generate Leaf Data based on a leaf_id over actual blockdata

### ISSUE THREAD

**Issue by Boy0000** [HibiscusMC/HMCLeaves#5]
configs would be alot easier to do if u only set 1 integer and the plugin determined the leafdata based on that.
might be able to use [this](https://github.com/MineInAbyss/Blocky/blob/master/src/main/kotlin/com/mineinabyss/blocky/BlockyPlugin.kt#L151-L162) to get an idea for it

**Comment by Fisher2911** [comment]
You can now do this with the state-id option
